// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1W78XHMw8baycVfX8Kkb2C22SWT38r8Y',
    appId: '1:79130569188:web:b1d6af1db24ef265bcfff1',
    messagingSenderId: '79130569188',
    projectId: 'study-up-uv',
    authDomain: 'study-up-uv.firebaseapp.com',
    storageBucket: 'study-up-uv.firebasestorage.app',
    measurementId: 'G-BPSPPGYS35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RNt61Q7z-5ljUdN_Ms7q7PpfQDbTElU',
    appId: '1:79130569188:android:8d1b939d178890e9bcfff1',
    messagingSenderId: '79130569188',
    projectId: 'study-up-uv',
    storageBucket: 'study-up-uv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTX4ZdrdHdpiiosehyiAFCn8DrEBNSPL0',
    appId: '1:79130569188:ios:c228ca6515a8c76ebcfff1',
    messagingSenderId: '79130569188',
    projectId: 'study-up-uv',
    storageBucket: 'study-up-uv.firebasestorage.app',
    iosBundleId: 'com.example.studyUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTX4ZdrdHdpiiosehyiAFCn8DrEBNSPL0',
    appId: '1:79130569188:ios:c228ca6515a8c76ebcfff1',
    messagingSenderId: '79130569188',
    projectId: 'study-up-uv',
    storageBucket: 'study-up-uv.firebasestorage.app',
    iosBundleId: 'com.example.studyUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1W78XHMw8baycVfX8Kkb2C22SWT38r8Y',
    appId: '1:79130569188:web:f06a490ce436d67fbcfff1',
    messagingSenderId: '79130569188',
    projectId: 'study-up-uv',
    authDomain: 'study-up-uv.firebaseapp.com',
    storageBucket: 'study-up-uv.firebasestorage.app',
    measurementId: 'G-PQSSVP8MQW',
  );
}
